# Generated by Django 4.2.18 on 2025-01-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_app', '0003_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
