# Generated by Django 4.2.18 on 2025-01-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_app', '0004_inventoryitem_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='threshold',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
