# Generated by Django 4.2.18 on 2025-01-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_app', '0005_inventoryitem_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='threshold',
            field=models.PositiveIntegerField(),
        ),
    ]
